project:
  type: book
  output-dir: docs

book:
  title: "CIUT Riesgo"
  author: "Nissim Lebovits"
  date: today
  chapters:
    - index.qmd
    - exposicion.qmd
    - suavizacion.qmd
    - renabap.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



