project:
  type: book
  output-dir: docs

book:
  title: "CIUT Riesgo"
  subtitle: "Leveraging Permitting and Zoning Data to Predict Upzoning Pressure in Philadelphia"
  author: "Nissim Lebovits"
  date: today

  chapters:
    - index.qmd
    - exposicion.qmd
    - suavizacion.qmd
    - renabap.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc_float: true
    theme: cosmo
    code-fold: true
    code-summary: "Mostrar código"
    number-sections: true
    fontsize: "11"
    lightbox: auto



